import os
import tempfile
import pandas as pd
from typing import Any, Dict, List, Optional
import plotly.graph_objects as go

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, Image
from reportlab.pdfgen import canvas

BG_COLOR = colors.HexColor("#0E1117")
PANEL_COLOR = colors.HexColor("#161B22")
TEXT_PRIMARY = colors.HexColor("#E6EDF3")
TEXT_SECONDARY = colors.HexColor("#8B949E")
ACCENT_GREEN = colors.HexColor("#00FF7F")
ACCENT_BLUE = colors.HexColor("#58A6FF")
ACCENT_RED = colors.HexColor("#F85149")
ACCENT_YELLOW = colors.HexColor("#E3B341")
BORDER_COLOR = colors.HexColor("#30363D")

ACCENT_GREEN_HEX = "#00FF7F"
ACCENT_BLUE_HEX = "#58A6FF"
TEXT_PRIMARY_HEX = "#E6EDF3"

def _draw_page_background(canvas_obj: canvas.Canvas, doc: SimpleDocTemplate) -> None:
    canvas_obj.saveState()
    canvas_obj.setFillColor(BG_COLOR)
    canvas_obj.rect(0, 0, doc.pagesize[0], doc.pagesize[1], fill=1, stroke=0)

    canvas_obj.setFillColor(TEXT_SECONDARY)
    canvas_obj.setFont("Helvetica-Bold", 9)
    canvas_obj.drawString(40, doc.pagesize[1] - 30, "CUESG | AI-POWERED ESG INTELLIGENCE DOSSIER")
    source_name = getattr(doc, "_source_name", "CUESG")
    canvas_obj.drawRightString(doc.pagesize[0] - 40, doc.pagesize[1] - 30, source_name)

    canvas_obj.setFillColor(TEXT_SECONDARY)
    canvas_obj.setFont("Helvetica", 8)
    canvas_obj.drawString(40, 30, "SEBI BRSR Principle 6 | CEA v20 Baseline | Generated by Autonomous AI Analyst")
    canvas_obj.drawRightString(doc.pagesize[0] - 40, 30, f"Page {canvas_obj.getPageNumber()}")

    canvas_obj.setStrokeColor(BORDER_COLOR)
    canvas_obj.setLineWidth(1)
    canvas_obj.line(40, 45, doc.pagesize[0] - 40, 45)
    canvas_obj.line(40, doc.pagesize[1] - 40, doc.pagesize[0] - 40, doc.pagesize[1] - 40)
    canvas_obj.restoreState()

def _create_dark_table(data: List[List[Any]], col_widths: Optional[List[float]] = None) -> Table:
    t = Table(data, colWidths=col_widths, repeatRows=1)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), PANEL_COLOR),
        ("TEXTCOLOR", (0, 0), (-1, 0), ACCENT_BLUE),
        ("ALIGN", (0, 0), (-1, -1), "LEFT"),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
        ("TOPPADDING", (0, 0), (-1, 0), 8),
        ("BACKGROUND", (0, 1), (-1, -1), BG_COLOR),
        ("TEXTCOLOR", (0, 1), (-1, -1), TEXT_PRIMARY),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 1), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [BG_COLOR, PANEL_COLOR]),
    ]))
    return t

def _try_render_figure(fig: go.Figure, width_inch: float, height_inch: float) -> Optional[Image]:
    try:
        import plotly.io as pio
        with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
            fig.write_image(tmp.name, width=int(width_inch * 96), height=int(height_inch * 96), scale=2)
            return Image(tmp.name, width=width_inch * inch, height=height_inch * inch)
    except Exception:
        return None

def _find_fig(figures: Dict[str, go.Figure], candidates: List[str]) -> Optional[go.Figure]:
    for key in candidates:
        if key in figures:
            return figures[key]
    return None

def build_pdf_report_v2(
    dossier_md: str,
    figures: Dict[str, go.Figure],
    chat_messages: List[Dict[str, Any]],
    rolling_context: str,
    package: Any,
    reg_engine: Any,
    ai_engine: Any,
    forecast_df: pd.DataFrame,
    mitigation_recs: Optional[List[str]] = None,
) -> bytes:
    
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("Title", parent=styles["Heading1"], fontName="Helvetica-Bold", fontSize=20, textColor=TEXT_PRIMARY, spaceAfter=15)
    h1_style = ParagraphStyle("H1", parent=styles["Heading2"], fontName="Helvetica-Bold", fontSize=13, textColor=ACCENT_BLUE, spaceBefore=20, spaceAfter=10)
    h2_style = ParagraphStyle("H2", parent=styles["Heading3"], fontName="Helvetica-Bold", fontSize=11, textColor=ACCENT_GREEN, spaceBefore=15, spaceAfter=8)
    body_style = ParagraphStyle("Body", fontName="Helvetica", fontSize=9, textColor=TEXT_PRIMARY, leading=14, spaceAfter=8)
    bullet_style = ParagraphStyle("Bullet", fontName="Helvetica", fontSize=9, textColor=TEXT_PRIMARY, leading=14, leftIndent=15, bulletIndent=5, spaceAfter=5)
    
    kpi_val_style = ParagraphStyle("KPI_Val", fontName="Helvetica-Bold", fontSize=15, textColor=TEXT_PRIMARY, alignment=1)
    kpi_val_green = ParagraphStyle("KPI_Val_G", fontName="Helvetica-Bold", fontSize=15, textColor=ACCENT_GREEN, alignment=1)
    kpi_lbl_style = ParagraphStyle("KPI_Lbl", fontName="Helvetica", fontSize=8, textColor=TEXT_SECONDARY, alignment=1)

    elements = []
    s = package.summary

    energy_fig = _find_fig(figures, ["Monthly Energy", "trend", "Monthly Energy Consumption"])
    forecast_fig = _find_fig(figures, ["12-Month Forecast", "forecast", "12-Month Forecast Outlook"])

    elements.append(Paragraph("CUESG COMPLIANCE & EMISSIONS DOSSIER", title_style))
    elements.append(Paragraph(f"<b>Data Source:</b> {package.source_name} | <b>Reporting Period:</b> {s['reporting_start'].strftime('%b %Y')} to {s['reporting_end'].strftime('%b %Y')}", body_style))
    elements.append(Spacer(1, 0.2 * inch))

    score_table = Table(
        [
            [Paragraph("TOTAL PORTFOLIO CARBON FOOTPRINT", kpi_lbl_style)],
            [Paragraph(f"<font size=34 color='{ACCENT_GREEN_HEX}'>{s['total_carbon']:,.1f}</font>", kpi_val_style)],
            [Paragraph("Metric Tonnes of CO₂e (Scope 1 + 2 + 3)", kpi_lbl_style)],
        ],
        colWidths=[3.5 * inch],
    )
    score_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), PANEL_COLOR),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("BOX", (0, 0), (-1, -1), 1, BORDER_COLOR),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
    ]))
    elements.append(score_table)
    elements.append(Spacer(1, 0.3 * inch))

    kpi_data = [
        [Paragraph("Active Assets", kpi_lbl_style), Paragraph("Total Records", kpi_lbl_style), Paragraph("Total Energy (kWh)", kpi_lbl_style)],
        [Paragraph(f"{s['assets']}", kpi_val_style), Paragraph(f"{s['records']:,}", kpi_val_style), Paragraph(f"{s['energy_total']:,.0f}", kpi_val_green)],
        [Paragraph("Scope 1 (Direct)", kpi_lbl_style), Paragraph("Scope 2 (Grid)", kpi_lbl_style), Paragraph("AI Anomalies Flagged", kpi_lbl_style)],
        [Paragraph(f"{s['scope1_total']:,.1f} tCO₂e", kpi_val_style), Paragraph(f"{s['scope2_total']:,.1f} tCO₂e", kpi_val_style), Paragraph(f"<font color='#F85149'>{s['anomaly_count']}</font>", kpi_val_style)],
    ]
    t_kpi = Table(kpi_data, colWidths=[2.3 * inch, 2.3 * inch, 2.3 * inch])
    t_kpi.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), PANEL_COLOR),
        ("GRID", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
    ]))
    elements.append(t_kpi)
    elements.append(PageBreak())

    elements.append(Paragraph("02 - EXECUTIVE SUMMARY & AI ADVISORY", h1_style))
    
    total_area = float(package.df["floor_area_sqm"].sum())
    avg_eui = s["energy_total"] / max(total_area, 1.0)
    
    p1 = f"The evaluated portfolio consists of {s['assets']} facilities encompassing {s['records']} telemetry records. The aggregate carbon liability stands at <b>{s['total_carbon']:,.1f} tCO₂e</b>. Scope 2 (purchased grid electricity) drives the vast majority of emissions at {s['scope2_total']:,.1f} tCO₂e, heavily influenced by the CEA 0.727 kg/kWh baseline."
    p2 = f"The portfolio's aggregate Energy Use Intensity (EUI) is <b>{avg_eui:.1f} kWh/m²</b>. The Machine Learning anomaly engine (Isolation Forest) identified <b>{s['anomaly_count']} statistically significant outliers</b>, indicating potential physical leakage, sensor drift, or inefficient HVAC base-loading."
    elements.append(Paragraph(p1, body_style))
    elements.append(Paragraph(p2, body_style))

    elements.append(Paragraph("Materiality & Risk Matrix", h2_style))
    mat_data = [
        ["Total Carbon Output", "GHG Management", "Environmental", "CRITICAL"],
        ["Energy Use Intensity", "Energy Optimization", "Environmental", "HIGH"],
        ["Water Benchmarking", "Resource Scarcity", "Environmental", "MEDIUM"],
        ["AI Anomaly Triggers", "Operational Integrity", "Governance", "HIGH"],
    ]
    elements.append(_create_dark_table([["Key Metric", "Material Topic", "ESG Pillar", "Risk/Priority"]] + mat_data, [2.0 * inch, 2.0 * inch, 1.5 * inch, 1.5 * inch]))
    
    elements.append(Paragraph("Automated CapEx & Mitigation Advisory", h2_style))
    elements.append(Paragraph("Based on the time-series data and emission gaps, the AI Omni-Agent recommends the following immediate actions to reduce compliance liability:", body_style))
    if mitigation_recs:
        for rec in mitigation_recs[:5]:
            elements.append(Paragraph(f"• {rec}", bullet_style))
    elements.append(PageBreak())

    elements.append(Paragraph("03 - CLIMATE ACTION & INVENTORY", h1_style))
    elements.append(Paragraph("Statutory GHG Emissions Breakdown", h2_style))
    ghg_data = [
        ["Scope 1 Direct", "Diesel combustion & leaks", f"{s['scope1_total']:,.1f}", "IPCC AR4: 2.68 kg/L"],
        ["Scope 2 Indirect", "Purchased grid electricity", f"{s['scope2_total']:,.1f}", "CEA v20: 0.727 kg/kWh"],
        ["Scope 3 Chain", "Water, e-waste & procurement", f"{s['scope3_total']:,.1f}", "SEBI BRSR Proxies"],
    ]
    elements.append(_create_dark_table([["Emission Scope", "Operational Source", "Total (tCO₂e)", "Statutory Factor"]] + ghg_data, [1.5 * inch, 2.5 * inch, 1.3 * inch, 1.7 * inch]))
    elements.append(Spacer(1, 0.2 * inch))

    if energy_fig is not None:
        img = _try_render_figure(energy_fig, 7.0, 3.2)
        if img:
            elements.append(img)
            elements.append(Spacer(1, 0.2 * inch))
    elements.append(PageBreak())

    elements.append(Paragraph("04 - RESOURCE EFFICIENCY TELEMETRY", h1_style))

    e_data = [
        ["Total Grid Consumption", f"{s['energy_total']:,.0f} kWh", "Facilities footprint"],
        ["Solar/Renewable Captured", f"{s['solar_total']:,.0f} kWh", "Rooftop PV off-sets"],
        ["Avg Energy Use Intensity", f"{avg_eui:.1f} kWh/m²", "Efficiency baseline"],
    ]
    elements.append(Paragraph("Energy Mechanics", h2_style))
    elements.append(_create_dark_table([["Telemetry Metric", "Aggregate Value", "Notes"]] + e_data, [2.5 * inch, 2.0 * inch, 2.5 * inch]))

    elements.append(Paragraph("Water Stewardship", h2_style))
    w_data = [
        ["Gross Water Withdrawal", f"{s['water_total']:,.0f} kL", "Potable + Tanker"],
        ["Intensity Benchmark Breaches", f"{int(package.df['Water_Benchmark_Breach'].sum())} flagged months", "BEE Compliance (EI-6)"],
    ]
    elements.append(_create_dark_table([["Water Metric", "Aggregate Value", "Notes"]] + w_data, [2.5 * inch, 2.0 * inch, 2.5 * inch]))
    elements.append(PageBreak())

    elements.append(Paragraph("05 - ASSET EFFICIENCY LEADERBOARD", h1_style))
    elements.append(Paragraph("Facilities ranked by Energy Intensity and Renewable adoption to identify portfolio laggards.", body_style))

    ranks = package.asset_rankings.sort_values(by="Energy_Intensity_kWh_per_sqm", ascending=True).head(15)
    rank_data = []
    for idx, row in enumerate(ranks.itertuples(), 1):
        rank_data.append([
            f"{idx}",
            str(row.asset_id),
            str(row.BEE_Rating),
            f"{row.Energy_Intensity_kWh_per_sqm:.2f}",
            f"{row.Scope1_tCO2e:,.1f}" if hasattr(row, 'Scope1_tCO2e') else "0.0",
            f"{row.Scope2_tCO2e:,.1f}",
            f"{row.Solar_Ratio * 100:.1f}%",
            str(int(row.Anomalies)),
        ])
    
    elements.append(_create_dark_table(
        [["Rank", "Asset ID", "BEE Rate", "EUI (kWh/m²)", "Scope 1", "Scope 2", "Solar %", "Anom."]] + rank_data,
        [0.4 * inch, 1.2 * inch, 0.8 * inch, 1.0 * inch, 0.9 * inch, 1.0 * inch, 0.9 * inch, 0.8 * inch],
    ))
    elements.append(PageBreak())

    elements.append(Paragraph("06 - MONTHLY EMISSIONS LEDGER", h1_style))
    monthly = (
        package.df
        .assign(mp=package.df["month"].dt.to_period("M").astype(str))
        .groupby("mp", as_index=False)
        .agg(energy=("energy_kwh", "sum"), s1=("Scope1_tCO2e", "sum"), s2=("Scope2_tCO2e", "sum"), s3=("Scope3_tCO2e", "sum"), anom=("Is_Anomaly", "sum"))
        .tail(20)
    )
    ledger_data = []
    for row in monthly.itertuples():
        ledger_data.append([
            row.mp,
            f"{row.energy:,.0f}",
            f"{row.s1:,.1f}",
            f"{row.s2:,.1f}",
            f"{row.s3:,.1f}",
            str(int(row.anom)),
        ])
    elements.append(_create_dark_table(
        [["Period", "Energy (kWh)", "Scope 1 (tCO₂e)", "Scope 2 (tCO₂e)", "Scope 3 (tCO₂e)", "Anomalies"]] + ledger_data,
        [1 * inch, 1.5 * inch, 1.2 * inch, 1.2 * inch, 1.2 * inch, 0.9 * inch],
    ))
    elements.append(PageBreak())

    elements.append(Paragraph("07 - ML FORECASTING & ANOMALIES", h1_style))

    if forecast_fig is not None:
        img = _try_render_figure(forecast_fig, 7.0, 2.6)
        if img:
            elements.append(img)

    elements.append(Paragraph("12-Month XGBoost Forecast", h2_style))
    f_monthly = forecast_df.groupby("month", as_index=False)[["Forecast_kWh", "Forecast_Scope2_tCO2e"]].sum().head(8)
    f_data = [[row.month.strftime("%b %Y"), f"{row.Forecast_kWh:,.0f} kWh", f"{row.Forecast_Scope2_tCO2e:,.1f} tCO₂e", "Monitor"] for row in f_monthly.itertuples()]
    elements.append(_create_dark_table([["Future Month", "Predicted Energy", "Predicted Scope 2", "Risk Flag"]] + f_data, [1.5 * inch, 2 * inch, 2 * inch, 1.5 * inch]))
    
    elements.append(Paragraph("Isolation Forest Alerts", h2_style))
    anoms = package.anomaly_records.head(8)
    a_data = []
    for _, row in anoms.iterrows():
        month_val = row.get("month", None)
        month_str = pd.to_datetime(month_val).strftime("%b %Y") if month_val is not None else "N/A"
        a_data.append([
            month_str,
            str(row.get("asset_id", "N/A")),
            str(row.get("Anomaly_Signature", "General_Operational_Anomaly")),
            f"{float(row.get('energy_kwh', 0)):,.0f}",
        ])
    if not a_data:
        a_data = [["N/A", "N/A", "No anomalies detected", "0"]]
    elements.append(_create_dark_table([["Period", "Asset", "Root-Cause Signature", "Energy (kWh)"]] + a_data, [1.0 * inch, 1.2 * inch, 3.3 * inch, 1.5 * inch]))
    elements.append(PageBreak())

    elements.append(Paragraph("08 - BRSR COMPLIANCE & AUDIT TRAIL", h1_style))

    elements.append(Paragraph("SEBI BRSR Principle 6 Checklist", h2_style))
    brsr_data = [
        ["EI-1: Total Energy Consumed", "Ready", f"{s['energy_total']:,.0f} kWh"],
        ["EI-2: Scope 1 Direct Emissions", "Ready", f"{s['scope1_total']:,.1f} tCO₂e (IPCC AR4)"],
        ["EI-3: Scope 2 Indirect (Grid)", "Ready", f"{s['scope2_total']:,.1f} tCO₂e (CEA v20)"],
        ["EI-6: Total Water Withdrawal", "Ready", f"{s['water_total']:,.0f} kL"],
    ]
    elements.append(_create_dark_table([["BRSR Indicator", "Status", "Evidentiary Data"]] + brsr_data, [2.5 * inch, 1 * inch, 3.5 * inch]))

    elements.append(Paragraph("Omni-Agent Chat Session Audit Trail", h2_style))
    elements.append(Paragraph("<i>The following interactions logged system intent and data manipulation commands for audit compliance.</i>", body_style))
    for msg in (chat_messages or [])[-12:]:
        role = str(msg.get("role", "system")).upper()
        content_raw = str(msg.get("content", "")).replace("\n", " ")
        content_truncated = content_raw[:200] + ("..." if len(content_raw) > 200 else "")
        color_hex = ACCENT_GREEN_HEX if role == "USER" else TEXT_PRIMARY_HEX
        elements.append(Paragraph(f"<font color='{color_hex}'><b>[{role}]</b></font> {content_truncated}", bullet_style))

    try:
        with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as pdf_buffer:
            pdf_path = pdf_buffer.name

        doc = SimpleDocTemplate(pdf_path, pagesize=A4, rightMargin=40, leftMargin=40, topMargin=50, bottomMargin=60)
        doc._source_name = getattr(package, "source_name", "CUESG")

        doc.build(elements, onFirstPage=_draw_page_background, onLaterPages=_draw_page_background)

        with open(pdf_path, "rb") as f:
            pdf_bytes = f.read()

        try:
            os.unlink(pdf_path)
        except OSError:
            pass

        return pdf_bytes

    except Exception as e:
        print(f"PDF Build Error: {e}")
        return b"%PDF-1.4\n% Failed to build PDF."
